// AUTO-GENERATED by web/scripts/generate-core-contract.mjs.
// Core headers are the source of truth. Do not edit this file manually.

export const CORE_WORLD_CHUNK_SPAN_GRID_CELLS =
  32 as const;

export const CORE_SIMULATION_MINUTES_PER_DAY =
  1440 as const;
